apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: membershipgroups.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: MembershipGroup
    listKind: MembershipGroupList
    plural: membershipgroups
    singular: membershipgroup
  versions:
    - name: v1beta3
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                term:
                  type: integer
                leader:
                  type: string