apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: partitiongroupmemberships.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: PartitionGroupMembership
    listKind: PartitionGroupMembershipList
    plural: partitiongroupmemberships
    singular: partitiongroupmembership
  versions:
    - name: v1beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - bind
          properties:
            bind:
              type: object
              required:
                - member
                - group
              properties:
                member:
                  type: string
                group:
                  type: string