apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: partitiongroups.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: PartitionGroup
    listKind: PartitionGroupList
    plural: partitiongroups
    singular: partitiongroup
  versions:
    - name: v1beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - partitions
              properties:
                partitions:
                  type: integer
                replicationFactor:
                  type: integer