apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: protocols.cloud.atomix.io
spec:
  group: cloud.atomix.io
  scope: Namespaced
  names:
    kind: Protocol
    listKind: ProtocolList
    plural: protocols
    singular: protocol
  versions:
    - name: v1beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - type
          properties:
            type:
              type: object
              properties:
                database:
                  type: object
                  required:
                    - metadata
                  properties:
                    metadata:
                      type: object
                      required:
                        - name
                      properties:
                        namespace:
                          type: string
                        name:
                          type: string
                gossip:
                  type: object
                  required:
                    - metadata
                  properties:
                    metadata:
                      type: object
                      required:
                        - name
                      properties:
                        namespace:
                          type: string
                        name:
                          type: string
                primaryBackup:
                  type: object
                  required:
                    - metadata
                  properties:
                    metadata:
                      type: object
                      required:
                        - name
                      properties:
                        namespace:
                          type: string
                        name:
                          type: string