apiVersion: storage.cloud.atomix.io/v1beta1
kind: RedisStorageClass
metadata:
  name: {{ template "redis-database.fullname" . }}
  labels:
    app: {{ template "redis-database.fullname" . }}
spec:
  proxy:
      image: {{ .Values.proxy.image.repository}}:{{.Values.proxy.image.tag}}
      imagePullPolicy: IfNotPresent
  backend:
    image: {{ .Values.backend.image.repository }}:{{.Values.backend.image.tag}}
    imagePullPolicy: IfNotPresent
    replicas: 1
