apiVersion: cloud.atomix.io/v1beta3
kind: Database
metadata:
  name: {{ template "redis-database.fullname" . }}
spec:
  partitions: {{ .Values.partitions }}
  storageClass:
    group: storage.cloud.atomix.io
    version: v1beta1
    kind: RedisStorageClass
    name: {{ template "redis-database.fullname" . }}
    namespace: {{ .Release.Namespace  }}



