{{- if eq (.Values.scope | lower) "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "raft-storage-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "raft-storage-controller.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "raft-storage-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}