apiVersion: v2
name: cache-database
description: Chart for configuring a cache storage class and database
kubeVersion: ">=1.17.0"
type: application
version: 0.3.0
appVersion: v0.1.0
keywords:
  - atomix
home: https://cloud.atomix.io
maintainers:
  - name: adib
    email: adib@opennetworking.org
  - name: kuujo
    email: jordan@opennetworking.org
