{{- if eq (.Values.scope | lower) "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "atomix-raft-storage-plugin.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "atomix-raft-storage-plugin.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "atomix-raft-storage-plugin.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}