replicas: 1

scope: Cluster

image:
  registry: ""
  repository: atomix/atomix-controller
  tag: v0.6.0
  pullPolicy: IfNotPresent
  pullSecrets: []

init:
  image:
    registry: ""
    repository: atomix/atomix-controller-init-certs
    tag: v0.6.0
    pullPolicy: IfNotPresent
    pullSecrets: []

broker:
  image:
    registry: ""
    repository: atomix/atomix-broker
    tag: v0.6.0
    pullPolicy: IfNotPresent
    pullSecrets: []
