{{- if eq (.Values.scope | lower) "namespace" }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cache-storage-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cache-storage-controller.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "cache-storage-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}