apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftclusters.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: RaftCluster
    listKind: RaftClusterList
    plural: raftclusters
    singular: raftcluster
  scope: Namespaced
  versions:
  - name: v2beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - clusterId
            properties:
              clusterId:
                type: integer
          status:
            type: object
            properties:
              state:
                type: string
                default: NotReady
    additionalPrinterColumns:
    - name: ID
      type: integer
      description: The cluster ID
      jsonPath: .spec.clusterId
    - name: Status
      type: string
      description: The cluster state
      jsonPath: .status.state