apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftpartitions.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: RaftPartition
    listKind: RaftPartitionList
    plural: raftpartitions
    singular: raftpartition
  scope: Namespaced
  versions:
  - name: v2beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - clusterId
            - partitionId
            properties:
              clusterId:
                type: integer
              partitionId:
                type: integer
          status:
            type: object
            properties:
              state:
                type: string
                default: NotReady
              leader:
                type: string
              term:
                type: integer
    additionalPrinterColumns:
    - name: ID
      type: integer
      description: The partition ID
      jsonPath: .spec.partitionId
    - name: Cluster
      type: integer
      description: The cluster to which the partition belongs
      jsonPath: .spec.clusterId
    - name: Leader
      type: string
      description: The current leader for the partition
      jsonPath: .status.leader
    - name: Term
      type: integer
      description: The current term for the partition
      jsonPath: .status.term
    - name: Status
      type: string
      description: The partition state
      jsonPath: .status.state