apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sets.primitives.atomix.io
spec:
  group: primitives.atomix.io
  scope: Namespaced
  names:
    kind: Set
    listKind: SetList
    plural: sets
    singular: set
  versions:
  - name: v2beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - store
            properties:
              store:
                type: object
                required:
                - name
                properties:
                  namespace:
                    type: string
                  name:
                    type: string
    additionalPrinterColumns:
    - name: Store
      type: string
      description: The primitive store
      jsonPath: .spec.store.name