apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storageplugins.atomix.io
spec:
  group: atomix.io
  scope: Cluster
  names:
    kind: StoragePlugin
    listKind: StoragePluginList
    plural: storageplugins
    singular: storageplugin
  versions:
  - name: v2beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - group
            - kind
            properties:
              group:
                type: string
              kind:
                type: string
              versions:
                type: array
                items:
                  type: object
                  required:
                  - name
                  - driver
                  properties:
                    name:
                      type: string
                    driver:
                      type: object
                      required:
                      - image
                      properties:
                        image:
                          type: string